apiVersion: apps/v1
kind: Deployment
metadata:
  name: natan-deployment
  labels:
    app: natan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: natan
  template:
    metadata:
      labels:
        app: natan
    spec:
      containers:
      - name: spring-boot-app
        image: natanstb/gs-spring-boot-docker 
        ports:
        - containerPort: 3000